# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: aaa2fca
_src_path: git@github.com:Quantco/copier-template-python
add_windows_tests_to_ci: false
github_remote: git@github.com:quantco/multiregex.git
github_user: jonashaag
project_name: multiregex
project_short_description: Quickly match many regexes against a string. Provides 2-10x speedups over naïve regex matching.
project_slug: multiregex

