# yaml-language-server: $schema=https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json
output: [summary]
templates:
  run: run --quiet --no-progress
no_auto_install: true
pre-commit:
  fail_on_changes: always
  exclude:
    - assets/**/*
  jobs:
    - name: pixi-install
      run: pixi install
    - group:
        parallel: true
        jobs:
          - name: ruff-check
            glob: "*.{py,pyi}"
            run: pixi {run} ruff check --fix --exit-non-zero-on-fix --force-exclude
          - name: ruff-format
            glob: "*.{py,pyi}"
            run: pixi {run} ruff format --force-exclude
          - name: mypy
            glob: "*.py"
            run: pixi {run} mypy {staged_files}
          - name: prettier
            glob: "*.{md,yml,yaml}"
            run: pixi {run} prettier --write --no-error-on-unmatched-pattern --list-different --ignore-unknown {staged_files}
          - name: taplo
            glob: "*.toml"
            run: pixi {run} taplo format {staged_files}
          - name: trailing-whitespace-fixer
            glob: "*"
            file_types: text
            run: pixi {run} trailing-whitespace-fixer {staged_files}
          - name: end-of-file-fixer
            glob: "*"
            file_types: text
            run: pixi {run} end-of-file-fixer {staged_files}
          - name: check-merge-conflict
            glob: "*"
            file_types: text
            run: pixi {run} check-merge-conflict --assume-in-merge {staged_files}
          - name: typos
            glob: "*"
            file_types: text
            run: pixi {run} typos --force-exclude {staged_files}
          - name: zizmor
            glob: "*.{yml,yaml}"
            run: pixi {run} zizmor --no-progress --min-severity high --fix .
