[project]
name = "multiregex"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.8"
pyahocorasick = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"

[feature.test.dependencies]
pytest = ">=6,<8"
pytest-cov = "*"
mypy = "*"
[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=multiregex --cov-report=xml --cov-report=term-missing"

[feature.build.dependencies]
build = "*"
[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."

[feature.lint.dependencies]
pre-commit = "*"
insert-license-header = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py38.dependencies]
python = "3.8.*"
[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py38 = ["py38", "test"]
py39 = ["py39", "test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
build = ["build"]
lint = { features = ["lint"], no-default-feature = true }
