[project]
name = "multiregex"
description = "Quickly match many regexes against a string. Provides 2-10x speedups over naïve regex matching."
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.8"
pyahocorasick = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"

[feature.test.dependencies]
pytest = ">=6,<8"
pytest-cov = "*"
pytest-md = "*"
pytest-emoji = "*"
mypy = "*"

[feature.build.dependencies]
build = "*"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."

[feature.test.tasks]
test = "pytest"

[feature.lint.dependencies]
pre-commit = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
pre-commit-hooks = "*"
typos = "*"
taplo = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py38.dependencies]
python = "3.8.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py38 = ["py38", "test"]
py312 = ["py312", "test"]
build = ["build"]
lint = ["lint"]
