from typing import Generic, Iterator, TypeVar

T = TypeVar("T")

class Automaton(Generic[T]):
    def add_word(self, word: str, value: T) -> bool: ...
    def make_automaton(self) -> bool: ...
    def iter(self, str) -> Iterator[tuple[str, T]]: ...
