
package:
  name: multiregex
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}{% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}.post{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}{% endif %}

source:
  git_url: ../


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check"


requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - pyahocorasick

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - multiregex

about:
  home: https://github.com/quantco/multiregex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Quickly match many regexes against a string'
  dev_url: https://github.com/QuantCo/multiregex

extra:
  recipe-maintainers:
    - jonashaag
